### ISSUE TITLE
Unit test doesn't work

### ISSUE THREAD

**Issue by eallais** [beothorn/webGrude#17]
`webGrude.BrowserTest  Time elapsed: 0.445 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/mortbay/jetty/Connector
	at com.github.tomakehurst.wiremock.jetty6.Jetty6HttpServerFactory.buildHttpServer(Jetty6HttpServerFactory.java:33)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:108)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule.<init>(WireMockClassRule.java:37)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule.<init>(WireMockClassRule.java:45)
	at webGrude.BrowserTest.<clinit>(BrowserTest.java:30)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: org.mortbay.jetty.Connector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
`

**Comment by beothorn** [comment]
@eallais I'm runnig the tests both from eclipse and with mvn clean test and it seems to be working.
From your stacktrace it seems that not finding the wiremock dependency.
Could you add more details on how are you trying to run these tests? From the command line or inside an IDE? What OS are you using?
Do you get the same error running
mvn clean install test
?

**Comment by eallais** [comment]
It's work on my linux computer. It seems to failed in Windows 10.
